name: mie451-assignment-sa
dependencies:
  - python=3.5.2
  - nb_conda
  - scipy=1.1.0
  - numpy=1.14.5
  - scikit-learn=0.19.2
  - pandas=0.23.4
  - tqdm=4.23.4
  - matplotlib=3.0.0
  - nltk=3.3
  - seaborn=0.9.0
